# Lab 1: Transformations with NumPy
You are now in a Jupyter notebook! It consists of written text, mixed with executable Python code.

You are supposed to read from top to bottom, and fill in code in the Python-blocks as you go.

## 1. Getting started
Familiarize yourself with the [NumPy quickstart](https://numpy.org/doc/stable/user/quickstart.html). You will need it to solve the following tasks.
Use the text, examples and links in the quickstart guide.

## 2. Get familiar with NumPy
First, import NumPy:

Press `Shift + Enter` to execute and advance to the next block. Repeat for each block. You can click on a block to edit and run the code again.
Press `Ctrl + Enter` to execute the current block without advancing.

In [2]:
import numpy as np


## a) Create vectors and matrices
#### Create the vector `t`

$\mathbf{t} =
\begin{bmatrix}
1 \\
0 \\
3
\end{bmatrix}
$

Hint: [https://numpy.org/doc/stable/user/quickstart.html#array-creation](https://numpy.org/doc/stable/user/quickstart.html#array-creation)

In [4]:
# TODO: Create the vector `t`
t = np.array([1, 0, 3])
print(f"t = {t}\nshape: {t.shape}\ntype: {type(t)}")

t = [1 0 3]
shape: (3,)
type: <class 'numpy.ndarray'>


It's important to note that the sequence of numbers in a one-dimensional NumPy "vector", like `np.array([1, 2, 3])`, is just numbers in a vector space and therefore neither a row nor a column vector. We can see that its shape is `(3,)`.

In order to use it with linear algebra, we have to explicitly go for a 2D representation.

#### Try to create `t` as a `N x 1` _column_ vector.


In [6]:
# TODO: Create 't' as a 'N x 1' column vector
t = t.reshape((3, 1))
print(f"\nt = \n{t}\nshape: {t.shape}")


t = 
[[1]
 [0]
 [3]]
shape: (3, 1)


#### Create the matrix `A`

$
\mathbf{A} =
\begin{bmatrix}
1 & 0 & 3\\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$

In [7]:
# TODO: Create the matrix A
A = np.array([[1,0,3],
              [4,5,6],
              [7,8,9]])
print(f"A:\n{A}")

A:
[[1 0 3]
 [4 5 6]
 [7 8 9]]


#### Create the identity matrix I.

$
\mathbf{I}=
\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$

Hint: [https://numpy.org/doc/stable/user/quickstart.html#functions-and-methods-overview](https://numpy.org/doc/stable/user/quickstart.html#functions-and-methods-overview)

In [8]:
# TODO: Create the matrix I
I = np.eye(3)
print(f"I:\n{I}")

I:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Create the matrix T.

$
\mathbf{T} =
\begin{bmatrix}
\mathbf{A} & \mathbf{t} \\
\mathbf{0} & 1
\end{bmatrix}
$

Hint: [https://numpy.org/doc/stable/user/quickstart.html#stacking-together-different-arrays](https://numpy.org/doc/stable/user/quickstart.html#stacking-together-different-arrays)
Hint: [https://numpy.org/doc/stable/reference/generated/numpy.block.html](https://numpy.org/doc/stable/reference/generated/numpy.block.html)

In [11]:
# TODO: Create the matrix T
T = np.hstack((A, t))
T = np.vstack((T, np.array([[0, 0, 0, 1]])))
print(f"T:\n{T}")

T:
[[1 0 3 1]
 [4 5 6 0]
 [7 8 9 3]
 [0 0 0 1]]


#### Create the matrix B.

$
\mathbf{B} = \mathbf{A}^T
$

Hint: [https://numpy.org/doc/stable/user/quickstart.html#changing-the-shape-of-an-array](https://numpy.org/doc/stable/user/quickstart.html#changing-the-shape-of-an-array)

In [12]:
# TODO: Create the matrix B
B = A.T
# or B = np.transpose(A)
print(f"A = \n{A}\nB = \n{B}")

A = 
[[1 0 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 4 7]
 [0 5 8]
 [3 6 9]]


## b) Coefficients
Set $t_2 = 2$ and $A_{12} = 2$, so that

   $\mathbf{t} =
    \begin{bmatrix}
    1 \\
    2 \\
    3
    \end{bmatrix},
    \:
    \mathbf{A} =
    \begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6 \\
    7 & 8 & 9
    \end{bmatrix}$

Perform the corresponding corrections to **T**, so that we still have

   $\mathbf{T} =
    \begin{bmatrix}
    \mathbf{A} & \mathbf{t} \\
    \mathbf{0} & 1
    \end{bmatrix}$

But hey, what happened to **B**?

In [14]:
# TODO: Solve b)
t = np.array([1, 2, 3])
A[0][1]=2
T[0][1]=2
T[1][3]=2
print(f"t:\n{t}\nA:\n{A},\nT:\n{T},\nB:\n{B}")

t:
[1 2 3]
A:
[[1 2 3]
 [4 5 6]
 [7 8 9]],
T:
[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]
 [0 0 0 1]],
B:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## c) Block operations
Extract the row vector

$\mathbf{r}_2 = \begin{bmatrix}A_{21} & A_{22} & A_{23}\end{bmatrix}$

and the column vector

$\mathbf{c}_2 = \begin{bmatrix}A_{12} \\ A_{22} \\ A_{32} \end{bmatrix}$

from **A**.

Extract the submatrix

$\mathbf{T}_{3 \times 4} = \begin{bmatrix}\mathbf{A} & \mathbf{t}\end{bmatrix}$

from **T**.

In [18]:
# TODO: r_2
r_2 = A[1,:]
print(f"r_2 = \n{r_2}\n")

# TODO: c_2
c_2 = A[:,1]
print(f"c_2 = \n{c_2}\n")

# TODO: T_3x4
T_3x4 = T[:3,:4]
print(f"T_3x4 = \n{T_3x4}")

r_2 = 
[4 5 6]

c_2 = 
[2 5 8]

T_3x4 = 
[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]]


Set the corresponding blocks in **A** and **T** to all `0` (so that the second row and column in **A** are all 0, and the upper 3x4 matrix in **T** is all 0).

Hint: [https://numpy.org/doc/stable/user/quickstart.html#copies-and-views](https://numpy.org/doc/stable/user/quickstart.html#copies-and-views)

In [28]:
# TODO: set 0
A = np.zeros((3,3))
tmp = np.hstack((A, t.reshape((3, 1))))
T[:3,:4] = tmp
print(f"A = \n{A}")
print(f"T = \n{T}")

A = 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
T = 
[[0 0 0 1]
 [0 0 0 2]
 [0 0 0 3]
 [0 0 0 1]]


## d) Matrix and vector arithmetic
- Add two vectors
- Add two matrices
- Multiply two matrices
- Take the dot product between two vectors
- Take the coefficient-wise multiplication between two matrices

Hint: [https://numpy.org/doc/stable/user/quickstart.html#basic-operations](https://numpy.org/doc/stable/user/quickstart.html#basic-operations)

In [29]:
# Replace 'None' with valid expressions.

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])

print(f"v1: {v1}\nv2: {v2}\n")
print(f"M:\n{M}\nN:\n{N}\n")

# TODO: Compute the sum of two vectors.
print(f"v1 + v2 = {v1 + v2}\n")

# TODO: Compute the sum of two matrices.
print(f"M + N = \n{M + N}\n")

# TODO: Compute the matrix multiplication of two matrices.
print(f"N matrix multiply M =\n{np.dot(N, M)}\n")

# TODO: Compute the dot product between two vectors.
print(f"v1 dot v2 = {np.dot(v1, v2)}\n")

# TODO: Compute the element-wise multiplication between two matrices.
print(f"M Element-wise product N =\n{np.multiply(M, N)}")

v1: [1 2 3]
v2: [4 5 6]

M:
[[1 2]
 [3 4]]
N:
[[5 6]
 [7 8]]

v1 + v2 = [5 7 9]

M + N = 
[[ 6  8]
 [10 12]]

N matrix multiply M =
[[23 34]
 [31 46]]

v1 dot v2 = 32

M Element-wise product N =
[[ 5 12]
 [21 32]]


## e) Reductions
- Take the sum of all elements in a matrix
- Compute the minimum value in a matrix
    - Also, find its position in the matrix
- Create a vector that is the maximum of each column in a matrix
- Find the L2-norm of a vector
- Find the number of elements in a vector that is greater than a given value.

In [43]:
# Replace 'None' with valid expressions
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
t = np.array([1,0,3])
# TODO: Take the sum of all elements in a matrix
# https://numpy.org/doc/stable/user/quickstart.html#basic-operations
print(f"sum of A: {A.sum()}")

# TODO: Compute the minimum value in a matrix
# TODO: Also, find its position in the matrix.
print(f"minimum of A: {A.min()} "
      f"at index {A.argmin()}, "
      f"(or for t={t}, {t.min()} at index {t.argmin()} in 2D)")

# TODO: Create a vector that is the maximum of each column in a matrix.
print(f"maximum of each column in A: {A.max(axis=0)}")

# TODO: Find the L2-norm of a vector.
v1 = np.array([1, 2, 3])
print(f"L2 norm of {v1} is {np.linalg.norm(v1)}")

# TODO: Find the number of elements in a vector that is greater than a given value.
# https://numpy.org/doc/stable/user/quickstart.html#changing-the-shape-of-an-array
v2 = np.array([1, 2, 3, 4, 5])*3
print(f"v2: {v2},\n"
      f"    {np.sum(v2 > 10)} elements are greater than 10")

sum of A: 45
minimum of A: 1 at index 0, (or for t=[1 0 3], 0 at index 1 in 2D)
maximum of each column in A: [7 8 9]
L2 norm of [1 2 3] is 3.7416573867739413
v2: [ 3  6  9 12 15],
    2 elements are greater than 10


Now that you have gotten to know NumPy, let's use it to transform images in the [next part of the lab](lab_01_transformations.ipynb)!